include("${CMAKE_CURRENT_LIST_DIR}/project_settings.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/conan_dependencies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/compiler_warnings.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/compiler_features.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/sanitizers.cmake")